/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package validador.de.vacunacion.Ventanas;

import javax.swing.JOptionPane;
import validador.de.vacunacion.ArbolBinarioB;
import validador.de.vacunacion.Conexion;
import validador.de.vacunacion.Graphviz;
import validador.de.vacunacion.Ventanas.BuscarRegABB;
import validador.de.vacunacion.Ventanas.ImprimirABBjF;

/**
 *
 * @author deyvi
 */
public class ArbolBinarioBJF extends javax.swing.JFrame {

    /**
     * Creates new form ArbolBinarioBJF
     */
    BuscarRegABB bcrR = new BuscarRegABB();
    ImprimirABBjF impR = new ImprimirABBjF();
    ArbolBinarioB arbolB = new ArbolBinarioB();
    CargarARCABBJF txtABB = new CargarARCABBJF();

    public ArbolBinarioBJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnBuscarR = new javax.swing.JButton();
        btnImprimirR = new javax.swing.JButton();
        jBtnGraphviz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMGuardarTXT = new javax.swing.JMenu();
        jMCargarABB = new javax.swing.JMenu();
        jMPersonalizado = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arbol Binario de Busqueda");

        jbtnBuscarR.setText("Buscar Registro");
        jbtnBuscarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnBuscarRMousePressed(evt);
            }
        });
        jbtnBuscarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarRActionPerformed(evt);
            }
        });

        btnImprimirR.setText("Imprimir todos los registros");
        btnImprimirR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImprimirRMousePressed(evt);
            }
        });

        jBtnGraphviz.setText("Imprimir Graphviz");
        jBtnGraphviz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnGraphvizMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-estructura-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jbtnBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnImprimirR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(jBtnGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBuscarR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMInicio.setBackground(new java.awt.Color(255, 255, 255));
        jMInicio.setForeground(new java.awt.Color(0, 0, 0));
        jMInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-casa-30.png"))); // NOI18N
        jMInicio.setText("Inicio");
        jMInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(jMInicio);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-engranaje-30.png"))); // NOI18N
        jMenu2.setText("Configuraciones");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });

        jMGuardarTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-30.png"))); // NOI18N
        jMGuardarTXT.setText("Guardar Arbol BB");
        jMGuardarTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMGuardarTXTMousePressed(evt);
            }
        });
        jMenu2.add(jMGuardarTXT);

        jMCargarABB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inscripción-30.png"))); // NOI18N
        jMCargarABB.setText("Cargar txt al ABB");
        jMCargarABB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMCargarABBMousePressed(evt);
            }
        });
        jMenu2.add(jMCargarABB);

        jMPersonalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-multiedición-30.png"))); // NOI18N
        jMPersonalizado.setText("Cargar Txt Personalizado");
        jMPersonalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMPersonalizadoMousePressed(evt);
            }
        });
        jMenu2.add(jMPersonalizado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInicioMousePressed
        this.dispose();
    }//GEN-LAST:event_jMInicioMousePressed

    private void jbtnBuscarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBuscarRActionPerformed

    private void jbtnBuscarRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarRMousePressed
        this.dispose();
        bcrR.setVisible(true);
    }//GEN-LAST:event_jbtnBuscarRMousePressed

    private void btnImprimirRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirRMousePressed
        this.dispose();
        impR.setVisible(true);
    }//GEN-LAST:event_btnImprimirRMousePressed

    private void jMGuardarTXTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMGuardarTXTMousePressed

        if (!arbolB.estaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea guardar el arbol en un .txt?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Conexion con = new Conexion();
                String rutaArchivo = "C:/Users/deyvi/Downloads/arbolBB.txt"; // Especifica la ruta del archivo aquí
                boolean conf = con.guardarABBTXT(arbolB.raiz, rutaArchivo);

                if (conf) {
                    JOptionPane.showMessageDialog(null, "Arbol Guardado Correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }


    }//GEN-LAST:event_jMGuardarTXTMousePressed

    private void jMCargarABBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCargarABBMousePressed
        txtABB.setVisible(true);
    }//GEN-LAST:event_jMCargarABBMousePressed

    private void jBtnGraphvizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGraphvizMousePressed
        // Guardar el árbol en un archivo DOT y generar la imagen

        Graphviz graphviz = new Graphviz();
        String rutaArchivoDOT = "arbolBB.dot";
        String rutaArchivoPNG = "arbolBB.png";
        graphviz.generarArchivoDOT(arbolB.raiz, rutaArchivoDOT);
        boolean resp = graphviz.generarImagenDesdeDOT(rutaArchivoDOT, rutaArchivoPNG);

        if (resp) {
            GraphvizABB gABB = new GraphvizABB(rutaArchivoPNG);
            gABB.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }


    }//GEN-LAST:event_jBtnGraphvizMousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMPersonalizadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPersonalizadoMousePressed
        CargarPersonalizadoABB crgarP = new CargarPersonalizadoABB();
        crgarP.setVisible(true);
    }//GEN-LAST:event_jMPersonalizadoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolBinarioBJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolBinarioBJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolBinarioBJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolBinarioBJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolBinarioBJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirR;
    private javax.swing.JButton jBtnGraphviz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMCargarABB;
    private javax.swing.JMenu jMGuardarTXT;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenu jMPersonalizado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton jbtnBuscarR;
    // End of variables declaration//GEN-END:variables
}
