/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package validador.de.vacunacion.Ventanas;

import javax.swing.JOptionPane;
import validador.de.vacunacion.ArbolAVL;
import validador.de.vacunacion.Conexion;
import validador.de.vacunacion.Graphviz;
import validador.de.vacunacion.Ventanas.BuscarRegistroAVL;

/**
 *
 * @author deyvi
 */
public class ArbolAVLJF extends javax.swing.JFrame {

    /**
     * Creates new form ArbolAVLJF
     */
    BuscarRegistroAVL buscarAVL = new BuscarRegistroAVL();
    ArbolAVL arbolAVL = new ArbolAVL();

    public ArbolAVLJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnBuscarRegistroAVL = new javax.swing.JButton();
        jBtnImprimirAVL = new javax.swing.JButton();
        jBtnGraphviz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMConfiguraciones = new javax.swing.JMenu();
        jMGuardarAVL = new javax.swing.JMenu();
        jMCargarAVL = new javax.swing.JMenu();
        jMPersonalizado = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arbol Binario AVL");

        jbtnBuscarRegistroAVL.setText("Buscar Registro");
        jbtnBuscarRegistroAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnBuscarRegistroAVLMousePressed(evt);
            }
        });

        jBtnImprimirAVL.setText("Imprimir todos los registros");
        jBtnImprimirAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnImprimirAVLMousePressed(evt);
            }
        });

        jBtnGraphviz.setText("Imprimir Graphviz");
        jBtnGraphviz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnGraphvizMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-estructura-96.png"))); // NOI18N

        jBtnAgregar.setText("Agregar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnBuscarRegistroAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jBtnImprimirAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jBtnGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnGraphviz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jbtnBuscarRegistroAVL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnImprimirAVL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));

        jMInicio.setBackground(new java.awt.Color(255, 255, 255));
        jMInicio.setForeground(new java.awt.Color(0, 0, 0));
        jMInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-casa-30.png"))); // NOI18N
        jMInicio.setText("Inicio");
        jMInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(jMInicio);

        jMConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-engranaje-30.png"))); // NOI18N
        jMConfiguraciones.setText("Configuraciones");

        jMGuardarAVL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-30.png"))); // NOI18N
        jMGuardarAVL.setText("Guardar Arbol AVL");
        jMGuardarAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMGuardarAVLMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMGuardarAVL);

        jMCargarAVL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inscripción-30.png"))); // NOI18N
        jMCargarAVL.setText("Cargar txt al AVL");
        jMCargarAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMCargarAVLMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMCargarAVL);

        jMPersonalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-multiedición-30.png"))); // NOI18N
        jMPersonalizado.setText("Cargar Txt Personalizado");
        jMPersonalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMPersonalizadoMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMPersonalizado);

        jMenuBar1.add(jMConfiguraciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInicioMousePressed
        this.dispose();
    }//GEN-LAST:event_jMInicioMousePressed

    private void jbtnBuscarRegistroAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarRegistroAVLMousePressed
        buscarAVL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBuscarRegistroAVLMousePressed

    private void jBtnImprimirAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnImprimirAVLMousePressed
        ImprimirAVLJF arbAVL = new ImprimirAVLJF();
        arbAVL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnImprimirAVLMousePressed

    private void jMGuardarAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMGuardarAVLMousePressed
        

        if (!arbolAVL.estaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea guardar el arbol en un .txt?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Conexion con = new Conexion();
                String rutaArchivo = "C:/Users/deyvi/Downloads/arbolAVL.txt"; //Ruta del archivo a guardar
                boolean conf = con.guardarAVLTXT(arbolAVL.raizAVL, rutaArchivo);

                if (conf) {
                    JOptionPane.showMessageDialog(null, "Arbol Guardado Correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "El Arbol esta vacio");
        }

    }//GEN-LAST:event_jMGuardarAVLMousePressed

    private void jMCargarAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCargarAVLMousePressed
        CargarARCAVLJF cAVL= new CargarARCAVLJF();
        cAVL.setVisible(true);
    }//GEN-LAST:event_jMCargarAVLMousePressed

    private void jBtnGraphvizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGraphvizMousePressed
        
            Graphviz graphviz = new Graphviz();
            String rutaArchivoDOT = "arbolAVL.dot";
            String rutaArchivoPNG = "arbolAVL.png";
            graphviz.generarArchivoDOT(arbolAVL.raizAVL, rutaArchivoDOT);
            boolean resp = graphviz.generarImagenDesdeDOT(rutaArchivoDOT, rutaArchivoPNG);

            if (resp) {
                GraphvizAVL gAVL=new GraphvizAVL(rutaArchivoPNG);
                gAVL.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
       
    }//GEN-LAST:event_jBtnGraphvizMousePressed

    private void jMPersonalizadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPersonalizadoMousePressed
        CargarPersonalizadoAVL cargarAVLP=new CargarPersonalizadoAVL();
        cargarAVLP.setVisible(true);
    }//GEN-LAST:event_jMPersonalizadoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolAVLJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnGraphviz;
    private javax.swing.JButton jBtnImprimirAVL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMCargarAVL;
    private javax.swing.JMenu jMConfiguraciones;
    private javax.swing.JMenu jMGuardarAVL;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenu jMPersonalizado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBuscarRegistroAVL;
    // End of variables declaration//GEN-END:variables
}
