/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package validador.de.vacunacion.Ventanas;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import validador.de.vacunacion.ArbolAVL;
import validador.de.vacunacion.CompresionHash;
import validador.de.vacunacion.Conexion;
import validador.de.vacunacion.GraficaAVL;
import validador.de.vacunacion.Graphviz;
import validador.de.vacunacion.NodoArbolAVL;
import validador.de.vacunacion.Ventanas.BuscarRegistroAVL;

/**
 *
 * @author deyvi
 */
public class ArbolAVLJF extends javax.swing.JFrame {

    /**
     * Creates new form ArbolAVLJF
     */
    BuscarRegistroAVL buscarAVL = new BuscarRegistroAVL();
    ArbolAVL arbolAVL = new ArbolAVL();

    public ArbolAVLJF() {
        initComponents();
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnBuscarRegistroAVL = new javax.swing.JButton();
        jBtnImprimirAVL = new javax.swing.JButton();
        jBtnGraphviz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jTfNombre = new javax.swing.JTextField();
        jTfDPI = new javax.swing.JTextField();
        jTfCantD = new javax.swing.JTextField();
        jTfV1 = new javax.swing.JTextField();
        jTfV2 = new javax.swing.JTextField();
        jTfV3 = new javax.swing.JTextField();
        jTfLugarV = new javax.swing.JTextField();
        jTfDepa = new javax.swing.JTextField();
        jTfMuni = new javax.swing.JTextField();
        jLbNombre = new javax.swing.JLabel();
        jLbDPI = new javax.swing.JLabel();
        jLbCantD = new javax.swing.JLabel();
        jLbV1 = new javax.swing.JLabel();
        jLbV2 = new javax.swing.JLabel();
        jLbV3 = new javax.swing.JLabel();
        jLbLugarV = new javax.swing.JLabel();
        jLbDepa = new javax.swing.JLabel();
        jLbMuni = new javax.swing.JLabel();
        jBtnGuardar = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMConfiguraciones = new javax.swing.JMenu();
        jMGuardarAVL = new javax.swing.JMenu();
        jMCargarAVL = new javax.swing.JMenu();
        jMPersonalizado = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMEncrypt = new javax.swing.JMenu();
        jMDesencrypt = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMComprimir = new javax.swing.JMenu();
        jMDescomprimir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arbol Binario AVL");

        jbtnBuscarRegistroAVL.setText("Buscar Registro");
        jbtnBuscarRegistroAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnBuscarRegistroAVLMousePressed(evt);
            }
        });

        jBtnImprimirAVL.setText("Imprimir todos los registros");
        jBtnImprimirAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnImprimirAVLMousePressed(evt);
            }
        });

        jBtnGraphviz.setText("Imprimir Graphviz");
        jBtnGraphviz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnGraphvizMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-estructura-96.png"))); // NOI18N

        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-añadir-usuario-masculino-30.png"))); // NOI18N
        jBtnAgregar.setText("Agregar:");
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAgregarMousePressed(evt);
            }
        });

        jLbNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNombre.setText("Nombre");

        jLbDPI.setForeground(new java.awt.Color(0, 0, 0));
        jLbDPI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDPI.setText("DPI");

        jLbCantD.setForeground(new java.awt.Color(0, 0, 0));
        jLbCantD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCantD.setText("Cantidad de Dosis");

        jLbV1.setForeground(new java.awt.Color(0, 0, 0));
        jLbV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV1.setText("Fecha Vacuna 1");

        jLbV2.setForeground(new java.awt.Color(0, 0, 0));
        jLbV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV2.setText("Fecha Vacuna 2");

        jLbV3.setForeground(new java.awt.Color(0, 0, 0));
        jLbV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV3.setText("Fecha Vacuna 3");

        jLbLugarV.setForeground(new java.awt.Color(0, 0, 0));
        jLbLugarV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbLugarV.setText("Lugar de Vacunacion");

        jLbDepa.setForeground(new java.awt.Color(0, 0, 0));
        jLbDepa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDepa.setText("Departamento de Vivienda");

        jLbMuni.setForeground(new java.awt.Color(0, 0, 0));
        jLbMuni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbMuni.setText("Municipio de Vivienda");

        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-15.png"))); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnGuardarMousePressed(evt);
            }
        });

        jBtnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-eliminar-15.png"))); // NOI18N
        jBtnCancel.setText("Cancelar");
        jBtnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCancelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLbLugarV, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jLbV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfLugarV)
                                    .addComponent(jTfV1)
                                    .addComponent(jTfNombre))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfDPI)
                                    .addComponent(jTfV2)
                                    .addComponent(jTfDepa)
                                    .addComponent(jLbDPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbDepa, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfCantD)
                                    .addComponent(jTfV3)
                                    .addComponent(jTfMuni)
                                    .addComponent(jLbCantD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbMuni, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jbtnBuscarRegistroAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jBtnImprimirAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jBtnGraphviz, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnGraphviz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jbtnBuscarRegistroAVL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnImprimirAVL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbNombre)
                            .addComponent(jLbDPI)
                            .addComponent(jLbCantD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfCantD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbV1)
                            .addComponent(jLbV2)
                            .addComponent(jLbV3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbLugarV)
                            .addComponent(jLbDepa)
                            .addComponent(jLbMuni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfLugarV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfDepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 23, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));

        jMInicio.setBackground(new java.awt.Color(255, 255, 255));
        jMInicio.setForeground(new java.awt.Color(0, 0, 0));
        jMInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-casa-30.png"))); // NOI18N
        jMInicio.setText("Inicio");
        jMInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMInicioMousePressed(evt);
            }
        });
        jMenuBar1.add(jMInicio);

        jMConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-engranaje-30.png"))); // NOI18N
        jMConfiguraciones.setText("Configuraciones");

        jMGuardarAVL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-30.png"))); // NOI18N
        jMGuardarAVL.setText("Guardar Arbol AVL");
        jMGuardarAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMGuardarAVLMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMGuardarAVL);

        jMCargarAVL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inscripción-30.png"))); // NOI18N
        jMCargarAVL.setText("Cargar txt al AVL");
        jMCargarAVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMCargarAVLMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMCargarAVL);

        jMPersonalizado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-multiedición-30.png"))); // NOI18N
        jMPersonalizado.setText("Cargar Txt Personalizado");
        jMPersonalizado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMPersonalizadoMousePressed(evt);
            }
        });
        jMConfiguraciones.add(jMPersonalizado);

        jMenuBar1.add(jMConfiguraciones);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-contraseña-30.png"))); // NOI18N
        jMenu1.setText("Encriptacion");

        jMEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-add-an-authentication-security-protection-isolated-only-white-background-30.png"))); // NOI18N
        jMEncrypt.setText("Encriptar");
        jMEncrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMEncryptMousePressed(evt);
            }
        });
        jMenu1.add(jMEncrypt);

        jMDesencrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-cryptography-30.png"))); // NOI18N
        jMDesencrypt.setText("Desencriptar");
        jMDesencrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMDesencryptMousePressed(evt);
            }
        });
        jMenu1.add(jMDesencrypt);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-compression-30.png"))); // NOI18N
        jMenu2.setText("Compresion");

        jMComprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-archivo-30.png"))); // NOI18N
        jMComprimir.setText(" Comprimir en txt");
        jMComprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMComprimirMousePressed(evt);
            }
        });
        jMenu2.add(jMComprimir);

        jMDescomprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-open-archive-30.png"))); // NOI18N
        jMDescomprimir.setText("Descomprimir txt");
        jMDescomprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMDescomprimirMousePressed(evt);
            }
        });
        jMenu2.add(jMDescomprimir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInicioMousePressed
        this.dispose();
        ocultarComponentes();
        vaciarComponentes();
    }//GEN-LAST:event_jMInicioMousePressed

    private void jbtnBuscarRegistroAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarRegistroAVLMousePressed
        buscarAVL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBuscarRegistroAVLMousePressed

    private void jBtnImprimirAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnImprimirAVLMousePressed
        ImprimirAVLJF arbAVL = new ImprimirAVLJF();
        arbAVL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnImprimirAVLMousePressed

    private void jMGuardarAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMGuardarAVLMousePressed

        if (!arbolAVL.estaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea guardar el arbol en un .txt?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Conexion con = new Conexion();
                String rutaArchivo = "arbolAVL.txt"; //Ruta del archivo a guardar
                boolean conf = con.guardarAVLTXT(arbolAVL.raizAVL, rutaArchivo);

                if (conf) {
                    JOptionPane.showMessageDialog(null, "Arbol Guardado Correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "El Arbol esta vacio");
        }

    }//GEN-LAST:event_jMGuardarAVLMousePressed

    private void jMCargarAVLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCargarAVLMousePressed
        CargarARCAVLJF cAVL = new CargarARCAVLJF();
        cAVL.setVisible(true);
    }//GEN-LAST:event_jMCargarAVLMousePressed

    private void jBtnGraphvizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGraphvizMousePressed
        GraficaAVL grap=new GraficaAVL();
        grap.setArbol(arbolAVL);

        JFrame gABB = new JFrame();
        gABB.getContentPane().add(grap);
        gABB.setSize(800, 600);
        gABB.setVisible(true);
    }//GEN-LAST:event_jBtnGraphvizMousePressed

    private void jMPersonalizadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMPersonalizadoMousePressed
        CargarPersonalizadoAVL cargarAVLP = new CargarPersonalizadoAVL();
        cargarAVLP.setVisible(true);
    }//GEN-LAST:event_jMPersonalizadoMousePressed

    private void jBtnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMousePressed
        mostrarComponentes();
    }//GEN-LAST:event_jBtnAgregarMousePressed

    private void jBtnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelMousePressed
        int opcion = JOptionPane.showConfirmDialog(null, "Desea cancelar?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            ocultarComponentes();
            vaciarComponentes();
        }

    }//GEN-LAST:event_jBtnCancelMousePressed

    private void jMEncryptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMEncryptMousePressed

        int opcion = JOptionPane.showConfirmDialog(null, "Desea encriptar el arbol?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            arbolAVL.encriptarAVL(arbolAVL.raizAVL, 3);
            JOptionPane.showMessageDialog(null, "Arbol encriptado");

        }
    }//GEN-LAST:event_jMEncryptMousePressed

    private void jMDesencryptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDesencryptMousePressed

        int opcion = JOptionPane.showConfirmDialog(null, "Desea desencriptar el arbol?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            arbolAVL.desencriptarAVL(arbolAVL.raizAVL, 3);
            JOptionPane.showMessageDialog(null, "Arbol desencriptado");

        }
    }//GEN-LAST:event_jMDesencryptMousePressed

    private void jBtnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarMousePressed
        try {
            long dpi = Long.parseLong(jTfDPI.getText());
            arbolAVL.insertar(jTfNombre.getText(), dpi);

            NodoArbolAVL editar = arbolAVL.buscarNodo(dpi, arbolAVL.raizAVL);

            try {
                editar.cantDosis = Integer.parseInt(jTfCantD.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Cantidad de dosis invalida");
                ocultarComponentes();
                vaciarComponentes();
            }

            editar.fecV1 = jTfV1.getText();
            editar.fecV2 = jTfV2.getText();
            editar.fecV3 = jTfV3.getText();
            editar.lugarV = jTfLugarV.getText();
            editar.depa = jTfDepa.getText();
            editar.muni = jTfMuni.getText();
            JOptionPane.showMessageDialog(null, "Registro agregado");
            ocultarComponentes();
            vaciarComponentes();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "DPI invalido");
        }
    }//GEN-LAST:event_jBtnGuardarMousePressed

    private void jMComprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMComprimirMousePressed
        if (!arbolAVL.estaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Desea Comprimir el arbol en un archivo de texto?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                CompresionHash comp = new CompresionHash();
                comp.guardarRegistros(arbolAVL.raizAVL);
                boolean resp = comp.guardartxtAVL("arbolAVLComprimido.txt");
                if (resp) {
                    JOptionPane.showMessageDialog(null, "Archivo comprimido guardado");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }
    }//GEN-LAST:event_jMComprimirMousePressed

    private void jMDescomprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDescomprimirMousePressed
        int opcion = JOptionPane.showConfirmDialog(null, "Desea Descomprimir un archivo?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                CompresionHash comp = new CompresionHash();
                comp.cargarTablaHashAVL("TablasHash/TablaHashAVL.txt");
                // Seleccionar Archivo
                String seleccion = "";
                JFileChooser jfc1 = new JFileChooser();
                FileNameExtensionFilter filtrado = new FileNameExtensionFilter("txt", "txt");
                jfc1.setFileFilter(filtrado);

                int respuesta = jfc1.showOpenDialog(this);

                if (respuesta == JFileChooser.APPROVE_OPTION) {
                    seleccion = jfc1.getSelectedFile().getPath();
                    comp.cargarTxtComprimidoAVL(seleccion);
                    
                }

            }   
    }//GEN-LAST:event_jMDescomprimirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolAVLJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolAVLJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnGraphviz;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnImprimirAVL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbCantD;
    private javax.swing.JLabel jLbDPI;
    private javax.swing.JLabel jLbDepa;
    private javax.swing.JLabel jLbLugarV;
    private javax.swing.JLabel jLbMuni;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JLabel jLbV1;
    private javax.swing.JLabel jLbV2;
    private javax.swing.JLabel jLbV3;
    private javax.swing.JMenu jMCargarAVL;
    private javax.swing.JMenu jMComprimir;
    private javax.swing.JMenu jMConfiguraciones;
    private javax.swing.JMenu jMDescomprimir;
    private javax.swing.JMenu jMDesencrypt;
    private javax.swing.JMenu jMEncrypt;
    private javax.swing.JMenu jMGuardarAVL;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenu jMPersonalizado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTfCantD;
    private javax.swing.JTextField jTfDPI;
    private javax.swing.JTextField jTfDepa;
    private javax.swing.JTextField jTfLugarV;
    private javax.swing.JTextField jTfMuni;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JTextField jTfV1;
    private javax.swing.JTextField jTfV2;
    private javax.swing.JTextField jTfV3;
    private javax.swing.JButton jbtnBuscarRegistroAVL;
    // End of variables declaration//GEN-END:variables

    private void ocultarComponentes() {
        jLbNombre.setVisible(false);
        jTfNombre.setVisible(false);
        jLbDPI.setVisible(false);
        jTfDPI.setVisible(false);
        jLbCantD.setVisible(false);
        jTfCantD.setVisible(false);
        jLbV1.setVisible(false);
        jTfV1.setVisible(false);
        jLbV2.setVisible(false);
        jTfV2.setVisible(false);
        jLbV3.setVisible(false);
        jTfV3.setVisible(false);
        jLbLugarV.setVisible(false);
        jTfLugarV.setVisible(false);
        jLbDepa.setVisible(false);
        jTfDepa.setVisible(false);
        jLbMuni.setVisible(false);
        jTfMuni.setVisible(false);

        jBtnGuardar.setVisible(false);
        jBtnCancel.setVisible(false);
    }

    private void mostrarComponentes() {
        jLbNombre.setVisible(true);
        jTfNombre.setVisible(true);
        jLbDPI.setVisible(true);
        jTfDPI.setVisible(true);
        jLbCantD.setVisible(true);
        jTfCantD.setVisible(true);
        jLbV1.setVisible(true);
        jTfV1.setVisible(true);
        jLbV2.setVisible(true);
        jTfV2.setVisible(true);
        jLbV3.setVisible(true);
        jTfV3.setVisible(true);
        jLbLugarV.setVisible(true);
        jTfLugarV.setVisible(true);
        jLbDepa.setVisible(true);
        jTfDepa.setVisible(true);
        jLbMuni.setVisible(true);
        jTfMuni.setVisible(true);

        jBtnGuardar.setVisible(true);
        jBtnCancel.setVisible(true);
    }

    private void vaciarComponentes() {
        jTfNombre.setText("");
        jTfDPI.setText("");
        jTfCantD.setText("");
        jTfV1.setText("");
        jTfV2.setText("");
        jTfV3.setText("");
        jTfLugarV.setText("");
        jTfDepa.setText("");
        jTfMuni.setText("");
    }
}
