/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package validador.de.vacunacion.Ventanas;

import javax.swing.JOptionPane;
import validador.de.vacunacion.ArbolBinarioB;
import validador.de.vacunacion.NodoArbolBinario;

/**
 *
 * @author deyvi
 */
public class BuscarRegABB extends javax.swing.JFrame {

    /**
     * Creates new form BuscarRegABB
     */
    ArbolBinarioB arbB = new ArbolBinarioB();
    long dpiBuscado;

    public BuscarRegABB() {
        initComponents();
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tFBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTfNombre = new javax.swing.JTextField();
        jTFDPI = new javax.swing.JTextField();
        jTFCantV = new javax.swing.JTextField();
        jTFV1 = new javax.swing.JTextField();
        jTFV2 = new javax.swing.JTextField();
        jTFV3 = new javax.swing.JTextField();
        jLbNombre = new javax.swing.JLabel();
        jLBDPI = new javax.swing.JLabel();
        jLBCantV = new javax.swing.JLabel();
        jLBV1 = new javax.swing.JLabel();
        jLBV2 = new javax.swing.JLabel();
        jLBV3 = new javax.swing.JLabel();
        jTFLugV = new javax.swing.JTextField();
        jTFDep = new javax.swing.JTextField();
        jTfMuni = new javax.swing.JTextField();
        jLBLugV = new javax.swing.JLabel();
        jLBDep = new javax.swing.JLabel();
        jlbMuni = new javax.swing.JLabel();
        jbtnGuardarEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlbTiempoBus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbEditarR = new javax.swing.JLabel();
        jbtnEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMVolver = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Registro");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-búsqueda-20.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DPI");

        jTFV1.setToolTipText("");

        jTFV2.setToolTipText("");

        jLbNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNombre.setText("Nombre");

        jLBDPI.setForeground(new java.awt.Color(0, 0, 0));
        jLBDPI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBDPI.setText("DPI");

        jLBCantV.setForeground(new java.awt.Color(0, 0, 0));
        jLBCantV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBCantV.setText("Cantidad de Dosis");

        jLBV1.setForeground(new java.awt.Color(0, 0, 0));
        jLBV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBV1.setText("Fecha Vacuna 1");

        jLBV2.setForeground(new java.awt.Color(0, 0, 0));
        jLBV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBV2.setText("Fecha Vacuna 2");

        jLBV3.setForeground(new java.awt.Color(0, 0, 0));
        jLBV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBV3.setText("Fecha Vacuna 3");

        jLBLugV.setForeground(new java.awt.Color(0, 0, 0));
        jLBLugV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBLugV.setText("Lugar de Vacunacion");

        jLBDep.setForeground(new java.awt.Color(0, 0, 0));
        jLBDep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBDep.setText("Departamento de  Vivienda");

        jlbMuni.setForeground(new java.awt.Color(0, 0, 0));
        jlbMuni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMuni.setText("Municipio de Vivienda");

        jbtnGuardarEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-15.png"))); // NOI18N
        jbtnGuardarEdit.setText("Guardar Info.");
        jbtnGuardarEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnGuardarEditMousePressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tiempo de busqueda");

        jlbTiempoBus.setBackground(new java.awt.Color(255, 255, 255));
        jlbTiempoBus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlbTiempoBus.setOpaque(true);

        jlbEditarR.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jlbEditarR.setForeground(new java.awt.Color(0, 0, 0));
        jlbEditarR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbEditarR.setText("Editar Registro");

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-basura-15.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar Registro");
        jbtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLBLugV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFLugV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLBV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFV1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(tFBuscar)))
                            .addComponent(jTfNombre))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(431, 431, 431)
                                .addComponent(jlbTiempoBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbEditarR, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFDPI)
                                        .addComponent(jTFV2)
                                        .addComponent(jLBDPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLBV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFDep)
                                        .addComponent(jLBDep, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFCantV)
                                    .addComponent(jTFV3)
                                    .addComponent(jLBCantV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLBV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfMuni)
                                    .addComponent(jlbMuni, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbtnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jlbTiempoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(11, 11, 11)
                .addComponent(jlbEditarR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBCantV)
                    .addComponent(jLBDPI)
                    .addComponent(jLbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCantV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBV3)
                    .addComponent(jLBV2)
                    .addComponent(jLBV1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMuni)
                    .addComponent(jLBDep)
                    .addComponent(jLBLugV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLugV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnGuardarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMVolver.setBackground(new java.awt.Color(255, 255, 255));
        jMVolver.setForeground(new java.awt.Color(0, 0, 0));
        jMVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-atrás-30.png"))); // NOI18N
        jMVolver.setText("Volver");
        jMVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMVolverMousePressed(evt);
            }
        });
        jMenuBar1.add(jMVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMVolverMousePressed
        ArbolBinarioBJF arbb = new ArbolBinarioBJF();
        this.dispose();
        arbb.setVisible(true);
        ocultarComponentes();
    }//GEN-LAST:event_jMVolverMousePressed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed
        if (!tFBuscar.getText().isEmpty()) {
            try {
                if (!arbB.estaVacio()) {
                    long dpiB = Long.parseLong(tFBuscar.getText());
                    long tiempoIni = System.nanoTime();
                    NodoArbolBinario busc = arbB.buscarNodo(dpiB);
                    long tiempofin = System.nanoTime();
                    long tiempotot = tiempofin - tiempoIni;
                    String tiempoTotal = Long.toString(tiempotot);
                    jlbTiempoBus.setText(tiempoTotal + " ns.");
                    if (busc != null) {
                        dpiBuscado = busc.dpi;
                        tFBuscar.setText("");
                        mostrarComponentes();
                        jTfNombre.setText(busc.nombre);
                        String dpiS = Long.toString(busc.dpi);
                        jTFDPI.setText(dpiS);
                        String cantDS = Integer.toString(busc.cantDosis);
                        jTFCantV.setText(cantDS);
                        jTFV1.setText(busc.fecV1);
                        jTFV2.setText(busc.fecV2);
                        jTFV3.setText(busc.fecV3);
                        jTFLugV.setText(busc.lugarV);
                        jTFDep.setText(busc.depa);
                        jTfMuni.setText(busc.muni);

                    } else {
                        JOptionPane.showMessageDialog(null, "La persona buscada aun no cuenta con vacuna contra Covid-19");
                        tFBuscar.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El arbol esta vacio");
                    tFBuscar.setText("");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese unicamente numeros de DPI");
                tFBuscar.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un numero de DPI");
            tFBuscar.setText("");
        }
    }//GEN-LAST:event_btnBuscarMousePressed

    private void jbtnGuardarEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGuardarEditMousePressed
        try {
            String nom = jTfNombre.getText();
            String dpis = jTFDPI.getText();
            long dpi = Long.parseLong(dpis);
            String cantS = jTFCantV.getText();
            int cantidad = Integer.parseInt(cantS);
            String fV1 = jTFV1.getText();
            String fV2 = jTFV2.getText();
            String fV3 = jTFV3.getText();
            String lugar = jTFLugV.getText();
            String depa = jTFDep.getText();
            String muni = jTfMuni.getText();

            boolean resp = arbB.actualizarNodo(nom, dpi, cantidad, fV1, fV2, fV3, lugar, depa, muni, dpiBuscado);

            if (resp) {
                JOptionPane.showMessageDialog(null, "Actualizacion completada");
                dpiBuscado = Long.parseLong(jTFDPI.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Actualizacion fallida");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }

    }//GEN-LAST:event_jbtnGuardarEditMousePressed

    private void jbtnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarMousePressed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            try {
                boolean conf = arbB.EliminarNodo(dpiBuscado);

                if (conf) {
                    JOptionPane.showMessageDialog(null, "Eliminacion correcta");
                    ocultarComponentes();
                    ArbolBinarioBJF arbolAABBV = new ArbolBinarioBJF();
                    arbolAABBV.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        } else {

        }
    }//GEN-LAST:event_jbtnEliminarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarRegABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarRegABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarRegABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarRegABB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarRegABB().setVisible(true);
            }
        });
    }

    private void ocultarComponentes() {
        jLbNombre.setVisible(false);
        jTfNombre.setVisible(false);
        jLBDPI.setVisible(false);
        jTFDPI.setVisible(false);
        jLBCantV.setVisible(false);
        jTFCantV.setVisible(false);
        jLBV1.setVisible(false);
        jTFV1.setVisible(false);
        jLBV2.setVisible(false);
        jTFV2.setVisible(false);
        jLBV3.setVisible(false);
        jTFV3.setVisible(false);
        jLBLugV.setVisible(false);
        jTFLugV.setVisible(false);
        jLBDep.setVisible(false);
        jTFDep.setVisible(false);
        jlbMuni.setVisible(false);
        jTfMuni.setVisible(false);
        jbtnGuardarEdit.setVisible(false);
        jlbEditarR.setVisible(false);
        jbtnEliminar.setVisible(false);
        jlbTiempoBus.setText("");
    }

    private void mostrarComponentes() {
        jLbNombre.setVisible(true);
        jTfNombre.setVisible(true);
        jLBDPI.setVisible(true);
        jTFDPI.setVisible(true);
        jLBCantV.setVisible(true);
        jTFCantV.setVisible(true);
        jLBV1.setVisible(true);
        jTFV1.setVisible(true);
        jLBV2.setVisible(true);
        jTFV2.setVisible(true);
        jLBV3.setVisible(true);
        jTFV3.setVisible(true);
        jLBLugV.setVisible(true);
        jTFLugV.setVisible(true);
        jLBDep.setVisible(true);
        jTFDep.setVisible(true);
        jlbMuni.setVisible(true);
        jTfMuni.setVisible(true);
        jbtnGuardarEdit.setVisible(true);
        jlbEditarR.setVisible(true);
        jbtnEliminar.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLBCantV;
    private javax.swing.JLabel jLBDPI;
    private javax.swing.JLabel jLBDep;
    private javax.swing.JLabel jLBLugV;
    private javax.swing.JLabel jLBV1;
    private javax.swing.JLabel jLBV2;
    private javax.swing.JLabel jLBV3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JMenu jMVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCantV;
    private javax.swing.JTextField jTFDPI;
    private javax.swing.JTextField jTFDep;
    private javax.swing.JTextField jTFLugV;
    private javax.swing.JTextField jTFV1;
    private javax.swing.JTextField jTFV2;
    private javax.swing.JTextField jTFV3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTfMuni;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardarEdit;
    private javax.swing.JLabel jlbEditarR;
    private javax.swing.JLabel jlbMuni;
    private javax.swing.JLabel jlbTiempoBus;
    private javax.swing.JTextField tFBuscar;
    // End of variables declaration//GEN-END:variables
}
