/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package validador.de.vacunacion.Ventanas;

import javax.swing.JOptionPane;
import validador.de.vacunacion.ArbolAVL;
import validador.de.vacunacion.NodoArbolAVL;

/**
 *
 * @author deyvi
 */
public class BuscarRegistroAVL extends javax.swing.JFrame {

    /**
     * Creates new form BuscarRegistroAVL
     */
    
    ArbolAVL arbolAVL=new ArbolAVL();
    long dpiBuscado;
    
    public BuscarRegistroAVL() {
        initComponents();
        OcultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbTiempoBus = new javax.swing.JLabel();
        jBtnBuscar = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlbEditar = new javax.swing.JLabel();
        jTfNombre = new javax.swing.JTextField();
        jTfDPI = new javax.swing.JTextField();
        jTfCantidadD = new javax.swing.JTextField();
        jlbNombre = new javax.swing.JLabel();
        jLbDPI = new javax.swing.JLabel();
        jLbCantidadD = new javax.swing.JLabel();
        jTfV1 = new javax.swing.JTextField();
        jTfV2 = new javax.swing.JTextField();
        jTfV3 = new javax.swing.JTextField();
        jLbV1 = new javax.swing.JLabel();
        jLbV2 = new javax.swing.JLabel();
        jLbV3 = new javax.swing.JLabel();
        jTfLugarV = new javax.swing.JTextField();
        jTfDep = new javax.swing.JTextField();
        jTfMuni = new javax.swing.JTextField();
        jLbLugarV = new javax.swing.JLabel();
        jLbDep = new javax.swing.JLabel();
        jLbMuni = new javax.swing.JLabel();
        jbtnEliminarRegistro = new javax.swing.JButton();
        jbtnGuardarReg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMVolver = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Registro");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tiempo de busqueda");

        jLbTiempoBus.setBackground(new java.awt.Color(204, 204, 204));
        jLbTiempoBus.setForeground(new java.awt.Color(0, 0, 0));
        jLbTiempoBus.setOpaque(true);

        jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-búsqueda-20.png"))); // NOI18N
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnBuscarMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DPI");

        jlbEditar.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jlbEditar.setForeground(new java.awt.Color(0, 0, 0));
        jlbEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbEditar.setText("Editar Registro");

        jlbNombre.setForeground(new java.awt.Color(0, 0, 0));
        jlbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNombre.setText("Nombre");

        jLbDPI.setForeground(new java.awt.Color(0, 0, 0));
        jLbDPI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDPI.setText("DPI");

        jLbCantidadD.setForeground(new java.awt.Color(0, 0, 0));
        jLbCantidadD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCantidadD.setText("Cantidad de Dosis");

        jLbV1.setForeground(new java.awt.Color(0, 0, 0));
        jLbV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV1.setText("Fecha Vacuna 1");

        jLbV2.setForeground(new java.awt.Color(0, 0, 0));
        jLbV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV2.setText("Fecha Vacuna 2");

        jLbV3.setForeground(new java.awt.Color(0, 0, 0));
        jLbV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbV3.setText("Fecha Vacuna 3");

        jLbLugarV.setForeground(new java.awt.Color(0, 0, 0));
        jLbLugarV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbLugarV.setText("Lugar de Vacunacion");

        jLbDep.setForeground(new java.awt.Color(0, 0, 0));
        jLbDep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbDep.setText("Departamiento de Vivienda");

        jLbMuni.setForeground(new java.awt.Color(0, 0, 0));
        jLbMuni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbMuni.setText("Municipio de Vivienda");

        jbtnEliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-basura-15.png"))); // NOI18N
        jbtnEliminarRegistro.setText("Eliminar Registro");
        jbtnEliminarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnEliminarRegistroMousePressed(evt);
            }
        });

        jbtnGuardarReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-guardar-15.png"))); // NOI18N
        jbtnGuardarReg.setText("Guardar Info.");
        jbtnGuardarReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnGuardarRegMousePressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbLugarV, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTfLugarV)
                            .addComponent(jLbV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTfV1)
                            .addComponent(jlbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTfNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLbDep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(jTfDep, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbV2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfV2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbDPI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfDPI, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfCantidadD)
                                    .addComponent(jLbCantidadD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfV3)
                                    .addComponent(jLbV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfMuni)
                                    .addComponent(jLbMuni, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jbtnGuardarReg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jtfBuscar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbTiempoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbTiempoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jlbEditar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(jLbDPI)
                    .addComponent(jLbCantidadD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfCantidadD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbV1)
                    .addComponent(jLbV2)
                    .addComponent(jLbV3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbLugarV)
                    .addComponent(jLbDep)
                    .addComponent(jLbMuni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfLugarV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfMuni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEliminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGuardarReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(67, 67, 67))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 153));

        jMVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-atrás-30.png"))); // NOI18N
        jMVolver.setText("Volver");
        jMVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMVolverMousePressed(evt);
            }
        });
        jMenuBar1.add(jMVolver);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarMousePressed
        if(!jtfBuscar.getText().isEmpty()){
            try{
                if(!arbolAVL.estaVacio()){
                   long dpiB=Long.parseLong(jtfBuscar.getText());
                   long tiempoIni= System.nanoTime();
                   NodoArbolAVL busc=arbolAVL.buscarNodo(dpiB, arbolAVL.raizAVL);
                   long tiempofin=System.nanoTime();
                   long tiempotot=tiempofin-tiempoIni;
                   String tiempoTotal=Long.toString(tiempotot);
                   jLbTiempoBus.setText(tiempoTotal+" ns.");
                if(busc!=null){
                    dpiBuscado=busc.dpi;
                    jtfBuscar.setText("");
                    System.out.println(busc.nombre+"  "+busc.dpi);
                    mostrarComponentes();
                    jTfNombre.setText(busc.nombre);
                    String dpiS=Long.toString(busc.dpi);
                    jTfDPI.setText(dpiS);
                    String cantDS=Integer.toString(busc.cantDosis);
                    jTfCantidadD.setText(cantDS);
                    jTfV1.setText(busc.fecV1);
                    jTfV2.setText(busc.fecV2);
                    jTfV3.setText(busc.fecV3);
                    jTfLugarV.setText(busc.lugarV);
                    jTfDep.setText(busc.depa);
                    jTfMuni.setText(busc.muni);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "La persona buscada aun no cuenta con vacuna contra Covid-19");
                    jtfBuscar.setText("");
                } 
                }else{
                    JOptionPane.showMessageDialog(null, "El arbol esta vacio");
                    jtfBuscar.setText("");
                }
                
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese unicamente numeros de DPI");
                jtfBuscar.setText("");
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un numero de DPI");
            jtfBuscar.setText("");
        }
    }//GEN-LAST:event_jBtnBuscarMousePressed

    private void jMVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMVolverMousePressed
        ArbolAVLJF arbol=new ArbolAVLJF();
        arbol.setVisible(true);
        this.dispose();
        OcultarComponentes();
    }//GEN-LAST:event_jMVolverMousePressed

    private void jbtnGuardarRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGuardarRegMousePressed
        try{
           String nom=jTfNombre.getText();
           String dpis=jTfDPI.getText();
           long dpi=Long.parseLong(dpis);
           String cantS=jTfCantidadD.getText();
           int cantidad=Integer.parseInt(cantS);
           String fV1=jTfV1.getText();
           String fV2=jTfV2.getText();
           String fV3=jTfV3.getText();
           String lugar=jTfLugarV.getText();
           String depa=jTfDep.getText();
           String muni=jTfMuni.getText();
           
           boolean resp=arbolAVL.actualizarNodo(nom, dpi, cantidad, fV1, fV2, fV3, lugar, depa, muni, dpiBuscado);
           
           if(resp){
               JOptionPane.showMessageDialog(null, "Actualizacion completada");
               dpiBuscado=Long.parseLong(jTfDPI.getText());
           }else{
               JOptionPane.showMessageDialog(null, "Actualizacion fallida");
           }
           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
           }
           
    }//GEN-LAST:event_jbtnGuardarRegMousePressed

    private void jbtnEliminarRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarRegistroMousePressed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            try{
                boolean conf=arbolAVL.eliminar(dpiBuscado);
                
                if(conf){
                    JOptionPane.showMessageDialog(null, "Eliminacion correcta");
                    OcultarComponentes();
                    ArbolAVLJF arbolAVLV=new ArbolAVLJF();
                    arbolAVLV.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar");
                }
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
            }
        } else {
            
        }
    }//GEN-LAST:event_jbtnEliminarRegistroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistroAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistroAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistroAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarRegistroAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarRegistroAVL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbCantidadD;
    private javax.swing.JLabel jLbDPI;
    private javax.swing.JLabel jLbDep;
    private javax.swing.JLabel jLbLugarV;
    private javax.swing.JLabel jLbMuni;
    private javax.swing.JLabel jLbTiempoBus;
    private javax.swing.JLabel jLbV1;
    private javax.swing.JLabel jLbV2;
    private javax.swing.JLabel jLbV3;
    private javax.swing.JMenu jMVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTfCantidadD;
    private javax.swing.JTextField jTfDPI;
    private javax.swing.JTextField jTfDep;
    private javax.swing.JTextField jTfLugarV;
    private javax.swing.JTextField jTfMuni;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JTextField jTfV1;
    private javax.swing.JTextField jTfV2;
    private javax.swing.JTextField jTfV3;
    private javax.swing.JButton jbtnEliminarRegistro;
    private javax.swing.JButton jbtnGuardarReg;
    private javax.swing.JLabel jlbEditar;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables

public void OcultarComponentes(){
    jlbEditar.setVisible(false);
    jlbNombre.setVisible(false);
    jTfNombre.setVisible(false);
    jLbDPI.setVisible(false);
    jTfDPI.setVisible(false);
    jLbCantidadD.setVisible(false);
    jTfCantidadD.setVisible(false);
    jLbV1.setVisible(false);
    jTfV1.setVisible(false);
    jLbV2.setVisible(false);
    jTfV2.setVisible(false);
    jLbV3.setVisible(false);
    jTfV3.setVisible(false);
    jLbLugarV.setVisible(false);
    jTfLugarV.setVisible(false);
    jLbDep.setVisible(false);
    jTfDep.setVisible(false);
    jLbMuni.setVisible(false);
    jTfMuni.setVisible(false);
    jbtnEliminarRegistro.setVisible(false);
    jbtnGuardarReg.setVisible(false);
    jLbTiempoBus.setText("");
}

public void mostrarComponentes(){
    jlbEditar.setVisible(true);
    jlbNombre.setVisible(true);
    jTfNombre.setVisible(true);
    jLbDPI.setVisible(true);
    jTfDPI.setVisible(true);
    jLbCantidadD.setVisible(true);
    jTfCantidadD.setVisible(true);
    jLbV1.setVisible(true);
    jTfV1.setVisible(true);
    jLbV2.setVisible(true);
    jTfV2.setVisible(true);
    jLbV3.setVisible(true);
    jTfV3.setVisible(true);
    jLbLugarV.setVisible(true);
    jTfLugarV.setVisible(true);
    jLbDep.setVisible(true);
    jTfDep.setVisible(true);
    jLbMuni.setVisible(true);
    jTfMuni.setVisible(true);
    jbtnEliminarRegistro.setVisible(true);
    jbtnGuardarReg.setVisible(true);
}

}
